name: rna-seq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.12
  - jupyterlab
  - ipykernel
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - fastqc
  - multiqc
  - salmon
  - subread
  - samtools
  - r-base
  - r-ggplot2
  - r-pheatmap
  - bioconductor-deseq2
  - bioconductor-clusterprofiler
  - bioconductor-org.hs.eg.db
  - bioconductor-org.mm.eg.db
